export enum CardType {
    artefact = 'Artifact',
    conspiracy = 'Conspiracy',
    creature = 'Creature',
    enchantement = 'Enchantment',
    ephemere = 'Instant',
    terrain = 'Land',
    phenomene = 'Phenomenon',
    plane = 'Plane',
    planeswalker = 'Planeswalker',
    scheme = 'Scheme',
    rituel = 'Sorcery',
    tribal = 'Tribal',
    vanguard = 'Vanguard',
}
