const apiConfigurationUrl = '/api/v1/';

export const ENVIRONMENT = {
    apiConfigurationUrl: apiConfigurationUrl,
    apiCardsConfigurationURL: `${apiConfigurationUrl}apicards`,
    apiCollectionCardsConfigurationURL: `${apiConfigurationUrl}collection-cards`,
    apiLoginConfigurationURL: `${apiConfigurationUrl}login`,
    apiRegisterConfigurationURL: `${apiConfigurationUrl}register`,
    apiCheckAvailabilityConfigurationURL: `${apiConfigurationUrl}check-availability`,
    apiFilterConfigurationUrl: `${apiConfigurationUrl}filters`,
    apiLogoutConfigurationURL: `${apiConfigurationUrl}logout`,
    apiVerifyTokenURL: `${apiConfigurationUrl}verify-token`,
    apiPasswordForgottenConfigurationURL: `${apiConfigurationUrl}password-forgotten`,
    apiNewPasswordConfigurationURL: `${apiConfigurationUrl}new-password`,
    apiMarketCardsURL: `${apiConfigurationUrl}marketcards`,
    apiCardAdURL: `${apiConfigurationUrl}card-ad`,
    apiCardAdOffersURL: `${apiConfigurationUrl}offer/card-ad`,
    apiOffer: `${apiConfigurationUrl}offer`,
    apiUser: `${apiConfigurationUrl}users`,
  apiUpdateUsernameURL: `${apiConfigurationUrl}users/update-username`,
  apiUpdatePasswordURL: `${apiConfigurationUrl}users/update-password`,
  apiUpdateUserURL: `${apiConfigurationUrl}users/update-infos`,
  apiVerifyPasswordURL: `${apiConfigurationUrl}users/verify-password`,
  apiDeleteUserURL: `${apiConfigurationUrl}users/delete`,
    url: 'http://localhost:8080',
};
